org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.debug=false
failOnNoDiscoveredTests=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.247
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

#jei_version=19.43.0.395
version_jei=238222:8607685
version_thutapi=1.0.5

## Mod Properties
# The mod version. See https://semver.org/
mod_version=4.2.0
mod_id=pokecube

mod_group_id=pokecube
compile_name=pokecube-aio

# Sub mod versions
version_thutcore=10.0.-1
version_pokecube_core=7.0.-1
version_wearables=4.0.-1
version_bling=3.0.-1