/*****************************************************************************
 * JEP - Java Math Expression Parser 2.3.1
 * January 26 2006
 * (c) Copyright 2004, Nathan Funk and Richard Morris
 * See LICENSE.txt for license information.
 *****************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTInteger.java */
package org.nfunk.jep;

/**
 * Constant Node
 */
public class ASTConstant extends SimpleNode
{
    private Object value;

    public ASTConstant(int id)
    {
        super(id);
    }

    public ASTConstant(Parser p, int id)
    {
        super(p, id);
    }

    public Object getValue()
    {
        return this.value;
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException
    {
        return visitor.visit(this, data);
    }

    public void setValue(Object val)
    {
        this.value = val;
    }

    @Override
    public String toString()
    {
        return "Constant: " + this.value;
    }
}
