package thut.core.common.commands;

import com.mojang.brigadier.exceptions.CommandSyntaxException;

import net.minecraft.command.CommandSource;
import net.minecraft.command.ICommandSource;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.util.text.TranslationTextComponent;
import net.minecraftforge.server.permission.DefaultPermissionLevel;
import net.minecraftforge.server.permission.PermissionAPI;

public class CommandTools
{
    public static boolean hasPerm(CommandSource source, String permission)
    {
        try
        {
            final ServerPlayerEntity player = source.asPlayer();
            return CommandTools.hasPerm(player, permission);
        }
        catch (final CommandSyntaxException e)
        {
            // TODO decide what to actually do here?
            return true;
        }
    }

    public static boolean hasPerm(ServerPlayerEntity player, String permission)
    { /*
       * Check if the node is registered, if not, register it as OP, and send
       * error message about this.
       */
        if (!PermissionAPI.getPermissionHandler().getRegisteredNodes().contains(permission))
        {
            final String message = "Autogenerated node, this is a bug and should be pre-registered.";
            PermissionAPI.getPermissionHandler().registerNode(permission, DefaultPermissionLevel.OP, message);
            System.err.println(message + ": " + permission);
        }
        return PermissionAPI.hasPermission(player, permission);
    }

    public static boolean isOp(ICommandSource sender, String permission)
    {
        /*
         * If sent by a player, check permissions, otherwise return true.
         */
        if (sender instanceof ServerPlayerEntity)
        {
            /*
             * Check if the node is registered, if not, register it as OP, and
             * send error message about this.
             */
            if (!PermissionAPI.getPermissionHandler().getRegisteredNodes().contains(permission))
            {
                final String message = "Autogenerated node, this is a bug and should be pre-registered.";
                PermissionAPI.getPermissionHandler().registerNode(permission, DefaultPermissionLevel.OP, message);
                System.err.println(message + ": " + permission);
            }
            return PermissionAPI.hasPermission((ServerPlayerEntity) sender, permission);
        }
        return true;
    }

    public static ITextComponent makeError(String text)
    {
        return CommandTools.makeTranslatedMessage(text, "red:italic");
    }

    public static ITextComponent makeTranslatedMessage(String key, String formatting, Object... args)
    {
        if (formatting == null) formatting = "";
        for (int i = 0; i < args.length; i++)
        {
            if (args[i] instanceof String) args[i] = new TranslationTextComponent((String) args[i]);

            if (!formatting.isEmpty() && args[i] instanceof ITextComponent)
            {
                final ITextComponent component = (ITextComponent) args[i];
                final String[] args2 = formatting.split(":");
                final String colour = args2[0].toUpperCase(java.util.Locale.ENGLISH);
                component.getStyle().setColor(TextFormatting.getValueByName(colour));
                if (args2.length > 1) for (int i1 = 1; i1 < args2.length; i1++)
                {
                    final String arg = args2[i1];
                    if (arg.equalsIgnoreCase("italic")) component.getStyle().setItalic(true);
                    if (arg.equalsIgnoreCase("bold")) component.getStyle().setBold(true);
                    if (arg.equalsIgnoreCase("underlined")) component.getStyle().setUnderlined(true);
                    if (arg.equalsIgnoreCase("strikethrough")) component.getStyle().setStrikethrough(true);
                    if (arg.equalsIgnoreCase("obfuscated")) component.getStyle().setObfuscated(true);
                }
            }
        }
        final TranslationTextComponent translated = new TranslationTextComponent(key, args);
        return translated;
    }

    public static void sendBadArgumentsMissingArg(ICommandSource sender)
    {
        sender.sendMessage(CommandTools.makeError("pokecube.command.invalidmissing"));
    }

    public static void sendBadArgumentsTryTab(ICommandSource sender)
    {
        sender.sendMessage(CommandTools.makeError("pokecube.command.invalidtab"));
    }

    public static void sendError(ICommandSource sender, String text)
    {
        sender.sendMessage(CommandTools.makeError(text));
    }

    public static void sendMessage(ICommandSource sender, String text)
    {
        final ITextComponent message = CommandTools.makeTranslatedMessage(text, null);
        sender.sendMessage(message);
    }

    public static void sendNoPermissions(ICommandSource sender)
    {
        sender.sendMessage(CommandTools.makeError("pokecube.command.noperms"));
    }
}
