modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="MIT"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="thut_bling"
version="${version_bling}"
displayName="Thut Bling"
authors="Thutmose"
description='''
Bling for Thut Wearables!
'''

[[dependencies.thut_bling]]
modId="thutcore"
mandatory=true
versionRange="[${version_thutcore},)"
ordering="NONE"
side="BOTH"

[[dependencies.thut_bling]]
modId="thut_wearables"
mandatory=true
versionRange="[${version_wearables},)"
ordering="NONE"
side="BOTH"

[[dependencies.thut_bling]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"
    
[[dependencies.thut_bling]]
modId="neoforge"
mandatory=true
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"