/*****************************************************************************
 * JEP - Java Math Expression Parser 2.3.1
 * January 26 2006
 * (c) Copyright 2004, Nathan Funk and Richard Morris
 * See LICENSE.txt for license information.
 *****************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTVarNode.java */

package org.nfunk.jep;

/**
 * Variable Node
 */
public class ASTVarNode extends SimpleNode
{

    // private String varName;
    private Variable var;

    public ASTVarNode(int id)
    {
        super(id);
        this.var = null;
    }

    public ASTVarNode(Parser p, int id)
    {
        super(p, id);
    }

    /**
     * Returns the name of the variable.
     */
    public String getName()
    {
        return this.var.getName();
    }

    public Variable getVar()
    {
        return this.var;
    }

    /**
     * Accept the visitor.
     */
    @Override
    public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException
    {
        return visitor.visit(this, data);
    }

    /**
     * Sets the name of the variable.
     */
    // public void setName(String varName_in)
    // {
    // var = varName_in;
    // }
    public void setVar(Variable variable)
    {
        this.var = variable;
    }

    /**
     * Creates a string containing the variable's name and value
     */
    @Override
    public String toString()
    {
        final String temp = "Variable: \"" + this.getName() + "\"";

        return temp;
    }
}
