modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="MIT"
issueTrackerURL="https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues" #optional

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="thutcore.mixins.json"

[[mixins]]
config="pokecube.mixins.json"

[[mods]]
modId="pokecube"
version="${mod_version}"
displayName="Pokécube Core"
authors="Thutmose"
description='''
Core mod for Pokécube Functionality
'''

[[mods]]
modId="pokecube_mobs"
version="${mod_version}"
displayName="Pokécube Mobs"
authors="Thutmose"
description='''
General mobs provider for Pokécube
'''

[[mods]]
modId="pokecube_adventures"
version="${mod_version}"
displayName="Pokécube Revival"
authors="Thutmose"
description='''
Additional Features for Pokécube..
'''

[[mods]]
modId="pokecube_legends"
version="${mod_version}"
displayName="Pokécube Legends"
authors="NelkGames, Thutmose"
description='''
Legendary Spawning mechanics for Pokécube..
'''

[[mods]]
modId="thutcore"
version="99.99.99"
displayName="Thut Core"
authors="Thutmose"
description='''
This is a library of shared functionality for my mods.

This is the version embedded into Pokécube, so use that for
the more reliable version number
'''

[[mods]]
modId="thutcrafts"
version="${mod_version}"
displayName="Thut Crafts"
authors="Thutmose"
description='''
Tech Demo mod for testing the elevator mod updates.
'''

[[mods]]
modId="thut_wearables"
version="${mod_version}"
displayName="Thut Wearables"
authors="Thutmose"
description='''
Accessories Slots for Minecraft!

This is the version embedded into Pokécube.
'''

[[mods]]
modId="thut_bling"
version="${mod_version}"
displayName="Thut Bling"
authors="Thutmose"
description='''
Bling for Thut Wearables!

This is the version embedded into Pokécube.
'''

[[dependencies.pokecube]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.pokecube]]
modId="neoforge"
mandatory=true
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"