modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="MIT"
issueTrackerURL="https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues" #optional

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="pokecube.mixins.json"

[[mods]]
modId="pokecube"
version="${version_pokecube_core}"
displayName="Pokécube Core"
authors="Thutmose"
description='''
Core mod for Pokécube Functionality
'''

[[mods]]
modId="pokecube_mobs"
version="${version_pokecube_core}"
displayName="Pokécube Mobs"
authors="Thutmose"
description='''
General mobs provider for Pokécube
'''

[[dependencies.pokecube]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.pokecube]]
modId="neoforge"
mandatory=true
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"